### ISSUE TITLE
Pronunciation is not standard.

### ISSUE THREAD

**Issue by pengpengtao** [bookbot-kids/g2p_id#19] opened 2024-11-26 01:39 UTC
Hello, I’m encountering a problem. I trained a TTS model for Indonesian, but there are three issues:
The overall intonation is not natural and smooth; it still sounds mechanical.
There are missing readings, such as: for "OJK", it only reads "OJ".
In some places, the intonation is strange. For example, the first half of the sentence has smooth and natural intonation, but towards the end, there is an abrupt rise or fall in pitch.

How should I address these issues?

**Comment by w11wo** [comment] 2024-11-26 02:14
Hi @pengpengtao.

> The overall intonation is not natural and smooth; it still sounds mechanical.

With regards to this, I think the issue is less to do with the g2p and more with the TTS. The g2p here simply converts Indonesian letters to the phoneme sounds they make, and do not contain any intonation information.

> There are missing readings, such as: for "OJK", it only reads "OJ".

I'm assuming you're running:

```py
>> g2p = G2p()
>> g2p("OJK")
[['o', 'dʒ', 'ʔ']]
```

which is definitely wrong. You may have to handle acronyms like those and split them into 3 letters:

```py
>> g2p("O J K")
[['o'], ['dʒ', 'e'], ['k', 'a']]
```

which adds the vowels to each letter, just as they are pronounced in the real world. Without the vowels, there would be just three consonant sounds O, J, and K pronounced consecutively, which is incorrect.

Hope this helps.

**Comment by pengpengtao** [comment] 2024-11-26 02:19
> 您好。
> 
> > 整体语调不自然流畅;它听起来仍然很机械。
> 
> 关于这一点，我认为问题与 g2p 关系不大，而与 TTS 关系更大。这里的 g2p 只是简单地将印尼字母转换为它们发出的音素发音，不包含任何语调信息。
> 
> > 有一些缺失的读数，例如：对于 “OJK”，它只读取 “OJ”。
> 
> 我假设你正在运行：
> 
> ```python
> >> g2p = G2p()
> >> g2p("OJK")
> [['o', 'dʒ', 'ʔ']]
> ```
> 
> 这绝对是错误的。您可能必须处理像这样的首字母缩略词并将它们分成 3 个字母：
> 
> ```python
> >> g2p("O J K")
> [['o'], ['dʒ', 'e'], ['k', 'a']]
> ```
> 
> 这会将元音添加到每个字母中，就像它们在现实世界中的发音一样。如果没有元音，就只有三个辅音 O、J 和 K 连续发音，这是不正确的。
> 
> 希望这有帮助。

ok！，thank u，In the phrase "Easy Cash," the AI pronunciation sounds like "S Cash." what should i do

**Comment by w11wo** [comment] 2024-11-26 02:24
@pengpengtao Similarly, using English words on our Indonesian g2p is out of scope. 

```py
>> g2p("easy cash")
[['e', 'a', 'ʃ'], ['tʃ', 'a', 's', 'h']] # wrong phonemization
```

which does lead to something that sounds like "ish chash" instead of "easy cash". You may need to manually handle English words if you want to normalize them into Indonesian phonemes, e.g.

```py
>> g2p("isi kesh") # manual mapping of English words to Indonesian-style pronunciation
[['i', 's', 'i'], ['k', 'e', 's', 'h']] # closer to "easy cash"
```

**Comment by pengpengtao** [comment] 2024-11-26 02:30
> 同样，在我们的印度尼西亚 g2p 上使用英语单词也超出了范围。
> 
> ```python
> >> g2p("easy cash")
> [['e', 'a', 'ʃ'], ['tʃ', 'a', 's', 'h']] # wrong phonemization
> ```
> 
> 这确实会导致听起来像 “ish chash” 而不是 “easy cash” 的东西。如果您想将英语单词规范化为印度尼西亚语音素，您可能需要手动处理英语单词，例如
> 
> ```python
> >> g2p("isi kesh") # manual mapping of English words to Indonesian-style pronunciation
> [['i', 's', 'i'], ['k', 'e', 's', 'h']] # closer to "easy cash"
> ```

But I'm not very familiar with handling English words as Indonesian phonemes, such as "VIP" and so on. I’ve been processing them directly as text. How should I learn to convert English words into Indonesian phonemes? I need your help.

**Comment by w11wo** [comment] 2024-11-26 02:34
@pengpengtao This is not a straightforward issue to handle and it's beyond the goal of this repository to handle, sorry. The task you'd like to accomplish is called English to Indonesian transliteration, i.e. English to Indonesian phoneme mapping. You can read more here: https://aclanthology.org/L12-1499/.

**Comment by pengpengtao** [comment] 2024-11-26 02:37
> @pengpengtao This is not a straightforward issue to handle and it's beyond the goal of this repository to handle, sorry. The task you'd like to accomplish is called English to Indonesian transliteration, i.e. English to Indonesian phoneme mapping. You can read more here: https://aclanthology.org/L12-1499/.

ok，thank u，i will learn it

**Comment by w11wo** [comment] 2024-11-26 02:39
Thanks. Closing.

**Closed as completed by w11wo** 2024-11-26 02:39 UTC
